add tests to project
bomarsche/Sprint_4 pull request #1
Opened 2023-03-25 11:23 UTC by bomarsche

Проект по тестированию Яндекс.Самокат

2023-03-25 16:39 UTC, pavel-ulan requested changes
Очень даже неплохо. Из недоработок - не все вопросы вынес и слишком перестарался с методом проверки. Поправь и будет ок

2023-03-25 16:39 UTC, pavel-ulan commented on src/test/java/SamokatPOMs/MainPage.java
> +            Thread.sleep(500); //без слипа периодически падают тесты, т.к. не успевает отобразиться блок с ответом.
**можно лучше**
можно использовать стандартное ожидание и указать блок FAQ как элемент для проверки. тогда он будет ждать пока блок не станет displayed. у тебя isFAQBlockDisplayed() не отрабатывает правильно или что? (у меня все прогружается быстро и даже без sleep все хорошо, так что я не могу проверить)
Просто sleep() ничего тебе не гарантирует, он просто тормозит поток. Из-за этого могут быть проблемы если используется несколько потоков например, ну и в целом так не принято.

2023-03-25 16:39 UTC, pavel-ulan commented on src/test/java/FAQTest.java
> +        };
**надо исправить**
а с остальными вопросами что? (дополни до целого списка пожалуйста)

2023-03-25 16:39 UTC, pavel-ulan commented on src/test/java/SamokatPOMs/MainPage.java
> +        Assert.assertTrue("Совпадения не найдены", isItemFound);
**надо исправить**
Метод конечно рабочий, но ты сильно переусложнил все.
первое - имя метода должно соответствовать тому, что он делает (getText, значит должен возвращать текст, а не проводить проверку). так что если прячешь проверку в метод, то и называй его checkSmT или textCheck или как-то аналогично. Суть - по имени теста должно быть понятно, что он делает проверку.
второе - зачем тебе для проверки цикл? У тебя уже все элементы в коллекции, можно просто нужный элемент из коллекции достать (по порядковому номеру или по полю элемента). Но ок, цикл еще можно понять (хотя я бы советовал разобраться с коллекциями и стримами, если знать эти темы глубоко, можно творить с множеством объектов магию в одну строчку). Но.... зачем тебе блок if (а после него еще и assertTrue)? чем тебя не устраивает старый добрый assertEquals?
В общем, переделай пожалуйста метод. Какое решение применить - решать тебе, ты можешь даже разбить его на несколько, но сейчас он слишком переусложнен, а должен быть максимально простым и коротким.

2023-03-26 12:42 UTC, bomarsche commented on src/test/java/SamokatPOMs/MainPage.java
> +            Thread.sleep(500); //без слипа периодически падают тесты, т.к. не успевает отобразиться блок с ответом.
Привет! Спасибо за подробный разбор
Метод переименовал, слип убрал. Метод постарался упростить (далее в след.комменте)

2023-03-26 12:42 UTC, bomarsche commented on src/test/java/FAQTest.java
> +        };
Дописал все пары вопрос-ответ

2023-03-26 12:44 UTC, bomarsche commented on src/test/java/SamokatPOMs/MainPage.java
> +        Assert.assertTrue("Совпадения не найдены", isItemFound);
Метод переименовал. Убрал всё лишнее. Перевести на коллекции/стримы пока не смог (не проходили ещё этого) - но буду копать в эту сторону.  Погонял на разных входных данных - всё работает.

2023-03-26 19:08 UTC, pavel-ulan approved these changes
👍

2023-03-27 04:49 UTC, merged